# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thomas Julou's homepage
author: Thomas Julou
email: thomas.julou@normalesup.org
description: >- # this means to ignore newlines until "baseurl:"
  I'm a biologist by training, did a PhD in biophysics lab, and currently work on basic research projects. 
  I like to combine different viewpoints in order to phrase new questions. I have a strong commitment to using quantitative approches, and use it to address biological problems involving phenotypic variability. In my daily work, I promote the use of open-source tools and reproducible research practices.
# Quantitative biology of microbes: from gene expression stochasticity to ecology and evolution of bacteria.

baseurl: "" # the subpath of your site, e.g. /blog
url: "julou.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-110860289-1
twitter_username: ThomasJulou
github_username:  julou
linkedin_username: thomasjulou

collections:
- projects

defaults:
  -
    scope:
      path: "_projects"
    values:
      published: true

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - projects.md
 - outputs.md
 - resources.md
 - notes.md
 - contact.md


# Build settings
markdown: kramdown
#theme: jekyll-skeleton
permalink: /notes/:categories/:title.html
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
